Baseurl = "/"
theme = "hugo-geo"
relativeURLs = true
languageCode = "en-us"
title = "My New Hugo Site"
disqusShortname = "shortcode-here"
paginate = 5
highlight = true
googleAnalytics = "G-DGNZ1CQ0D4"


[taxonomies]
	tag = "tags"
	tutorial = "email"

[params]
	showglobe = false

	favicon = "favicon.ico"

	googleAnalytics = "G-DGNZ1CQ0D4"

	email = "schiang317@gmail.com"

	profilepic = "img/profPic2.jpg"

	title = "Shuya Chiang"
	subtitle = "(She/Her/Hers)"

	# Social buttons for sidebar
	# Each of these are optional
	[[params.socialbuttons]]
	faicon = "github"
	url = "https://github.com/schiang3"

	[[params.socialbuttons]]
	faicon = "linkedin"
	url= "https://www.linkedin.com/in/shuyac"
	[[params.navlinks]]
	name = "About"
	url = "aboutme"

	[[params.navlinks]]
	name = "Blog"
	url = "post/"

	[[params.navlinks]]
	name = "Project"
	url = "project/"

        [[params.navlinks]]
        name = "Contact"
        url = "contact/"
